# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Id', models.IntegerField(default=0)),
                ('Event_Name', models.CharField(default='', max_length=200)),
                ('Event_Output', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Figure_Id', models.IntegerField(default=0)),
                ('Figure_Name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link_Id', models.IntegerField(default=0)),
                ('Link_Question', models.CharField(default='', max_length=200)),
                ('Causing_Event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causing_event', to='chatbot.Event_Node')),
                ('Leading_Event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_event', to='chatbot.Event_Node')),
            ],
        ),
        migrations.AddField(
            model_name='event_node',
            name='Figures',
            field=models.ManyToManyField(to='chatbot.Figure'),
        ),
    ]
