# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_node',
            old_name='Event_Output',
            new_name='Event_Aftermath',
        ),
        migrations.AddField(
            model_name='event_node',
            name='Event_Cause',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event_node',
            name='Event_Happen',
            field=models.TextField(default='', max_length=200),
        ),
    ]
