# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20171006_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_node',
            name='Event_Aftermath',
        ),
        migrations.RemoveField(
            model_name='event_node',
            name='Event_Cause',
        ),
        migrations.RemoveField(
            model_name='event_node',
            name='Event_Name',
        ),
    ]
