# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20171006_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_node',
            name='Event_Tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
