# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_event_node_event_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Tag_Id', models.IntegerField(default=0)),
                ('Event_Tag_Name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='event_node',
            name='Event_Tag',
        ),
        migrations.AddField(
            model_name='event_node',
            name='Event_Tag',
            field=models.ManyToManyField(to='chatbot.Event_Tag'),
        ),
    ]
