# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20171006_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curriculum_Name', models.TextField(default='')),
                ('Curriculum_Seed_Node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.Event_Node')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum_Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.Curriculum')),
                ('Dependencies', models.ManyToManyField(to='chatbot.Event_Node')),
                ('Event_Node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core', to='chatbot.Event_Node')),
            ],
        ),
    ]
