# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_curriculum_curriculum_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt_Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(default='')),
                ('Answer', models.TextField(default='')),
                ('Conditions', models.ManyToManyField(to='chatbot.Event_Node')),
                ('Curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.Curriculum')),
            ],
        ),
    ]
