# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_prompt_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt_condition',
            name='Conditions',
        ),
        migrations.AddField(
            model_name='prompt_condition',
            name='Exclude_Conditions',
            field=models.ManyToManyField(related_name='exclude_conditions', to='chatbot.Event_Node'),
        ),
        migrations.AddField(
            model_name='prompt_condition',
            name='Include_Conditions',
            field=models.ManyToManyField(related_name='include_conditions', to='chatbot.Event_Node'),
        ),
    ]
