# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20171116_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt_condition',
            old_name='Question',
            new_name='Question_Type',
        ),
        migrations.AddField(
            model_name='prompt_condition',
            name='Final_Reach_Node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reach_node', to='chatbot.Event_Node'),
        ),
    ]
