# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_auto_20171121_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt_condition',
            name='Question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='prompt_condition',
            name='Final_Reach_Node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reach_node', to='chatbot.Event_Node'),
        ),
    ]
