# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20171128_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_node',
            name='Event_Question',
            field=models.TextField(default=''),
        ),
    ]
