# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_auto_20171128_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_node',
            name='Figures',
        ),
        migrations.AddField(
            model_name='event_node',
            name='Figures',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Figure'),
            preserve_default=False,
        ),
    ]
