# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_auto_20171128_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_link',
            name='Causing_Event',
        ),
        migrations.RemoveField(
            model_name='question_link',
            name='Leading_Event',
        ),
        migrations.RemoveField(
            model_name='event_node',
            name='Event_Question',
        ),
        migrations.AddField(
            model_name='event_node',
            name='Event_Question',
            field=models.ManyToManyField(to='chatbot.Question_Link'),
        ),
    ]
