# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_auto_20171128_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='Subject_Figure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Figure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt_condition',
            name='Question_Type',
            field=models.TextField(blank=True, default=''),
        ),
    ]
