# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_auto_20171128_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_node',
            name='Prerequisite_Event',
            field=models.ManyToManyField(blank=True, null=True, related_name='prerequisite', to='chatbot.Event_Node'),
        ),
    ]
