# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_node',
            name='Containing_Tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='con', to='chatbot.Event_Tag'),
        ),
        migrations.AddField(
            model_name='event_node',
            name='Prerequisite_Tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='pre', to='chatbot.Event_Tag'),
        ),
    ]
